const movies = [
  {
    id: 1,
    title: 'Vingadores',
    subtitle: 'Vingadores Guerra Infinita',
    storyline: "Em Vingadores: Guerra Infinita, Thanos enfim chega à Terra, disposto a reunir as Joias do Infinito. Para enfrentá-lo, os Vingadores precisam unir forças com os Guardiões da Galáxia, ao mesmo tempo em que lidam com desavenças entre alguns de seus integrantes.",
    rating: 4.5,
    imagePath: 'images/vingadores-guerra-infinita.jpg',
    bookmarked: true,
    genre: 'action',
  },
  {
    id: 2,
    title: 'John Wick 2',
    subtitle: 'John Wick 2',
    storyline: 'Forçado a honrar uma dívida de sua vida passada, John Wick assassina um alvo que não desejava matar, depois é traído pelo mandante do crime.',
    rating: 4.8,
    imagePath: 'images/john-wick-2.jpg',
    bookmarked: false,
    genre: 'action',
  },
  {
    id: 3,
    title: 'O Auto da Compadecida',
    subtitle: 'O Auto da Compadecida',
    storyline: 'As aventuras dos nordestinos João Grilo, um sertanejo pobre e mentiroso, e Chicó, o mais covarde dos homens. Ambos lutam pelo pão de cada dia e atravessam por vários episódios enganando a todos do pequeno vilarejo de Taperoá, no sertão da Paraíba.',
    rating: 5,
    imagePath: 'images/o-auto-compadecida.jpg',
    bookmarked: false,
    genre: 'comedy',
  },
  {
    id: 4,
    title: 'Harry Potter',
    subtitle: 'Harry Potter e as Relíquias da Morte',
    storyline: "Em Harry Potter e as Relíquias da Morte - Parte 2, Harry Potter e seus amigos Rony Weasley e Hermione Granger seguem à procura das horcruxes. O objetivo do trio é encontrá-las e, em seguida, destruí-las, de forma a eliminar lorde Voldemort de uma vez por todas.",
    rating: 4.8,
    imagePath: 'images/harry-potter-e-as-reliquias-da-morte-parte-2.jpg',
    bookmarked: true,
    genre: 'fantasy',
  },
  {
    id: 5,
    title: 'Tenacius D',
    subtitle: 'Uma dupla infernal',
    storyline: "Esta é a história de uma amizade que mudou o curso da história do Rock n' Roll para sempre. O ingênuo JB se une ao relaxado KG para formar a banda Tenacious D. Eles pretendem escrever seus nomes na história da música, mas logo percebem que isso não é tão simples assim.'",
    rating: 4.2,
    imagePath: 'images/tenacius-D.jpg',
    bookmarked: true,
    genre: 'fantasy',
  },
];

export default movies;
